"use client"

import { useState, useEffect, useCallback } from "react"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { cn } from "@/lib/utils"
import { taskAPI, providerAPI, AgentTask, ProjectInfo } from "@/lib/api"
import type { AssistantModelProfile } from "@/lib/types"
import {
  Plus, CheckCircle2, XCircle, Loader2, AlertCircle, Clock,
  ChevronRight, ExternalLink, GitPullRequest, Copy,
  RotateCcw, ArrowUp, Folder, FolderPlus, GitBranch,
  FileText, Settings2, Search,
} from "lucide-react"
import { toast } from "@/hooks/use-toast"

// ─── Helpers ─────────────────────────────────────────────────────────────────

const STATUS = {
  0: { label: "等待中", icon: <Clock className="h-3.5 w-3.5" />, color: "text-muted-foreground" },
  1: { label: "执行中", icon: <Loader2 className="h-3.5 w-3.5 animate-spin" />, color: "text-blue-500" },
  2: { label: "已完成", icon: <CheckCircle2 className="h-3.5 w-3.5" />, color: "text-green-500" },
  3: { label: "失败",   icon: <XCircle className="h-3.5 w-3.5" />,        color: "text-destructive" },
  4: { label: "已取消", icon: <AlertCircle className="h-3.5 w-3.5" />,    color: "text-muted-foreground" },
} as const

function timeAgo(ts: number) {
  const d = Math.floor((Date.now() - ts * 1000) / 1000)
  if (d < 60) return `${d}s`
  if (d < 3600) return `${Math.floor(d / 60)}m`
  if (d < 86400) return `${Math.floor(d / 3600)}h`
  return `${Math.floor(d / 86400)}d`
}

// ─── Diff Viewer ──────────────────────────────────────────────────────────────

function DiffViewer({ diff }: { diff: string }) {
  const [copied, setCopied] = useState(false)
  if (!diff) return (
    <div className="flex items-center justify-center h-40 text-muted-foreground/40 text-sm">无文件改动</div>
  )
  const lines = diff.split("\n")
  const added   = lines.filter(l => l.startsWith("+") && !l.startsWith("+++")).length
  const removed = lines.filter(l => l.startsWith("-") && !l.startsWith("---")).length
  return (
    <div className="flex flex-col h-full min-h-0">
      <div className="flex items-center justify-between px-4 py-2 border-b border-border/50 shrink-0">
        <div className="flex items-center gap-3 text-xs">
          <span className="text-green-500 font-mono">+{added}</span>
          <span className="text-red-500 font-mono">-{removed}</span>
          <span className="text-muted-foreground">{lines.length} 行</span>
        </div>
        <Button variant="ghost" size="sm" className="h-6 px-2 text-xs gap-1"
          onClick={() => { navigator.clipboard.writeText(diff); setCopied(true); setTimeout(() => setCopied(false), 2000) }}>
          <Copy className="h-3 w-3" />{copied ? "已复制" : "复制"}
        </Button>
      </div>
      <div className="flex-1 overflow-auto">
        <pre className="text-[11px] font-mono p-4">
          {lines.map((line, i) => (
            <div key={i} className={cn("px-1 leading-relaxed whitespace-pre",
              line.startsWith("+++") || line.startsWith("---") ? "text-muted-foreground"
                : line.startsWith("+") ? "text-green-600 dark:text-green-400 bg-green-500/5"
                : line.startsWith("-") ? "text-red-500 bg-red-500/5"
                : line.startsWith("@@") ? "text-blue-500"
                : "text-foreground/80"
            )}>{line || " "}</div>
          ))}
        </pre>
      </div>
    </div>
  )
}

// ─── PR Dialog ────────────────────────────────────────────────────────────────

function PRDialog({ task, open, onClose }: { task: AgentTask; open: boolean; onClose: () => void }) {
  const [repoUrl, setRepoUrl]   = useState("")
  const [token, setToken]       = useState("")
  const [title, setTitle]       = useState(`[Juno Agent] ${task.title}`)
  const [body, setBody]         = useState(`Generated by Juno Agent.\n\n**Task:** ${task.prompt}\n\n**Summary:** ${task.result_summary}`)
  const [loading, setLoading]   = useState(false)
  const [prUrl, setPrUrl]       = useState("")

  const handleCreate = async () => {
    if (!repoUrl.trim() || !token) return
    setLoading(true)
    try {
      const res = await taskAPI.createPR({
        task_id: task.id, repo_url: repoUrl.trim(),
        github_token: token, pr_title: title, pr_body: body,
      })
      setPrUrl(res.pr_url)
    } catch (err: any) {
      toast({ title: "创建失败", description: err.message, variant: "destructive" })
    } finally { setLoading(false) }
  }
  return (
    <Dialog open={open} onOpenChange={v => !v && onClose()}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader><DialogTitle>创建 Pull Request</DialogTitle></DialogHeader>
        {prUrl ? (
          <div className="space-y-3">
            <div className="flex items-center gap-2 p-3 bg-green-500/10 rounded-xl border border-green-500/20">
              <CheckCircle2 className="h-5 w-5 text-green-500 shrink-0" />
              <a href={prUrl} target="_blank" rel="noopener noreferrer"
                className="text-sm text-green-600 dark:text-green-400 hover:underline flex items-center gap-1 truncate">
                {prUrl} <ExternalLink className="h-3 w-3 shrink-0" />
              </a>
            </div>
            <Button className="w-full" onClick={onClose}>关闭</Button>
          </div>
        ) : (
          <div className="space-y-3">
            <div><label className="text-xs text-muted-foreground block mb-1.5">GitHub 仓库地址</label>
              <Input value={repoUrl} onChange={e => setRepoUrl(e.target.value)} placeholder="https://github.com/owner/repo" className="font-mono text-sm" /></div>
            <div><label className="text-xs text-muted-foreground block mb-1.5">GitHub Token</label>
              <Input type="password" value={token} onChange={e => setToken(e.target.value)} placeholder="ghp_..." className="font-mono text-sm" /></div>
            <div><label className="text-xs text-muted-foreground block mb-1.5">PR 标题</label>
              <Input value={title} onChange={e => setTitle(e.target.value)} /></div>
            <div><label className="text-xs text-muted-foreground block mb-1.5">PR 描述</label>
              <Textarea value={body} onChange={e => setBody(e.target.value)} rows={4} className="text-sm font-mono resize-none" /></div>
            <div className="flex gap-2">
              <Button variant="outline" onClick={onClose} className="flex-1">取消</Button>
              <Button onClick={handleCreate} disabled={loading || !token || !repoUrl} className="flex-1 gap-1.5">
                {loading ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <GitPullRequest className="h-3.5 w-3.5" />}创建 PR
              </Button>
            </div>
          </div>
        )}
      </DialogContent>
    </Dialog>
  )
}

// ─── New Project Dialog ───────────────────────────────────────────────────────

function NewProjectDialog({ open, onClose, onCreate }: {
  open: boolean; onClose: () => void; onCreate: (name: string) => void
}) {
  const [name, setName] = useState("")
  const handleCreate = () => {
    if (!name.trim()) return
    onCreate(name.trim())
    setName("")
    onClose()
  }
  return (
    <Dialog open={open} onOpenChange={v => !v && onClose()}>
      <DialogContent className="sm:max-w-[360px]">
        <DialogHeader><DialogTitle>新建项目</DialogTitle></DialogHeader>
        <p className="text-sm text-muted-foreground -mt-2">
          将在服务器上创建 <code className="text-xs bg-muted px-1 py-0.5 rounded">workspace/&lt;uid&gt;/&lt;名称&gt;</code> 目录
        </p>
        <div className="flex gap-2">
          <Input value={name} onChange={e => setName(e.target.value)} placeholder="my-project"
            className="font-mono" autoFocus onKeyDown={e => e.key === "Enter" && handleCreate()} />
          <Button onClick={handleCreate} disabled={!name.trim()}>创建</Button>
        </div>
      </DialogContent>
    </Dialog>
  )
}

// ─── Task Panel ───────────────────────────────────────────────────────────────

function TaskPanel({ task, onClose, onRefresh }: {
  task: AgentTask; onClose: () => void; onRefresh: () => void
}) {
  const [showPR, setShowPR] = useState(false)
  const s = STATUS[task.status]
  return (
    <div className="fixed inset-y-0 right-0 w-[560px] bg-background border-l border-border/60 shadow-2xl flex flex-col z-40">
      <div className="px-5 py-4 border-b border-border/50 shrink-0">
        <div className="flex items-start justify-between gap-3">
          <div className="min-w-0 flex-1">
            <div className={cn("flex items-center gap-1.5 text-xs font-medium mb-1.5", s.color)}>
              {s.icon}{s.label}
            </div>
            <h2 className="font-semibold">{task.title}</h2>
            <p className="text-xs text-muted-foreground mt-1 font-mono">{task.branch || "默认工作区"}</p>
          </div>
          <div className="flex gap-1 shrink-0">
            <Button variant="ghost" size="icon" className="h-7 w-7" onClick={onRefresh}>
              <RotateCcw className="h-3.5 w-3.5" />
            </Button>
            <Button variant="ghost" size="icon" className="h-7 w-7" onClick={onClose}>
              <XCircle className="h-3.5 w-3.5" />
            </Button>
          </div>
        </div>
        {task.prompt && (
          <p className="mt-3 text-sm text-muted-foreground bg-muted/30 rounded-lg px-3 py-2.5 leading-relaxed">
            {task.prompt}
          </p>
        )}
      </div>

      <div className="flex-1 min-h-0 overflow-hidden flex flex-col">
        {task.status === 1 && (
          <div className="flex-1 flex flex-col items-center justify-center gap-3 text-muted-foreground">
            <div className="h-12 w-12 rounded-full border-2 border-blue-500/20 flex items-center justify-center">
              <Loader2 className="h-6 w-6 animate-spin text-blue-500" />
            </div>
            <div className="text-center">
              <p className="text-sm font-medium">AI 正在工作</p>
              <p className="text-xs text-muted-foreground/60 mt-1">正在读取代码、分析并进行修改</p>
            </div>
          </div>
        )}
        {task.status === 0 && (
          <div className="flex-1 flex items-center justify-center text-muted-foreground/40 text-sm">等待执行...</div>
        )}
        {task.status === 3 && (
          <div className="p-5">
            <div className="p-4 bg-destructive/10 rounded-xl border border-destructive/20">
              <p className="text-sm font-medium text-destructive mb-1.5">执行失败</p>
              <p className="text-xs text-muted-foreground font-mono">{task.error_msg}</p>
            </div>
          </div>
        )}
        {task.status === 2 && (
          <div className="flex flex-col flex-1 min-h-0">
            {task.result_summary && (
              <div className="px-5 py-3 border-b border-border/50 shrink-0">
                <p className="text-xs text-muted-foreground font-medium uppercase tracking-wide mb-1.5">执行摘要</p>
                <p className="text-sm text-foreground/80 leading-relaxed">{task.result_summary}</p>
              </div>
            )}
            <div className="flex items-center justify-between px-5 py-2.5 border-b border-border/50 shrink-0">
              <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">代码变更</p>
              {task.result_diff && (
                <Button size="sm" className="h-7 text-xs gap-1.5" onClick={() => setShowPR(true)}>
                  <GitPullRequest className="h-3.5 w-3.5" />创建 PR
                </Button>
              )}
            </div>
            <div className="flex-1 min-h-0 overflow-hidden">
              <DiffViewer diff={task.result_diff} />
            </div>
          </div>
        )}
      </div>
      {showPR && <PRDialog task={task} open={showPR} onClose={() => setShowPR(false)} />}
    </div>
  )
}

// ─── Main Page ────────────────────────────────────────────────────────────────

const SUGGESTIONS = [
  "分析项目结构，生成详细的 README 文档",
  "找出所有 TODO 注释并逐一解决",
  "添加单元测试，覆盖主要业务逻辑",
  "重构代码，消除重复逻辑",
  "修复所有 TypeScript 类型错误",
  "添加完整的错误处理",
]

export default function AgentsPage() {
  const [profiles, setProfiles]               = useState<AssistantModelProfile[]>([])
  const [selectedProfileId, setSelectedProfileId] = useState<number | null>(null)
  const [projects, setProjects]               = useState<ProjectInfo[]>([])
  const [activeProject, setActiveProject]     = useState<ProjectInfo | null>(null)
  const [tasks, setTasks]                     = useState<AgentTask[]>([])
  const [activeTaskId, setActiveTaskId]       = useState<number | null>(null)
  const [prompt, setPrompt]                   = useState("")
  const [submitting, setSubmitting]           = useState(false)
  const [showNewProject, setShowNewProject]   = useState(false)

  const loadAll = useCallback(async () => {
    try {
      const [profilesRes, tasksRes, projectsRes] = await Promise.all([
        providerAPI.listAssistantModelProfiles(),
        taskAPI.list(1, 100),
        taskAPI.listProjects(),
      ])
      const plist = profilesRes.list || []
      setProfiles(plist)
      if (plist.length > 0) setSelectedProfileId(p => p ?? plist[0].id)
      setTasks(tasksRes.list || [])
      const projList = projectsRes.list || []
      setProjects(projList)
      // Auto-select first project
      setActiveProject(p => p ?? projList[0] ?? null)
    } catch {}
  }, [])

  useEffect(() => { loadAll() }, [loadAll])

  // Poll running tasks
  useEffect(() => {
    const runningIds = tasks.filter(t => t.status === 1).map(t => t.id)
    if (!runningIds.length) return
    const iv = setInterval(async () => {
      await Promise.allSettled(runningIds.map(async id => {
        try {
          const updated = await taskAPI.get(id)
          setTasks(prev => prev.map(t => t.id === id ? updated : t))
        } catch {}
      }))
    }, 3000)
    return () => clearInterval(iv)
  }, [tasks.filter(t => t.status === 1).map(t => t.id).join(",")])

  const activeTask     = tasks.find(t => t.id === activeTaskId) ?? null
  const projectTasks   = activeProject
    ? tasks.filter(t => t.branch === activeProject.name || (activeProject.name === "默认工作区" && !t.branch))
    : []

  const handleSubmit = async () => {
    if (!prompt.trim() || !selectedProfileId || !activeProject) return
    setSubmitting(true)
    try {
      const task = await taskAPI.create({
        workspace_name: activeProject.name === "默认工作区" ? "" : activeProject.name,
        prompt: prompt.trim(),
        model_profile_id: selectedProfileId,
      })
      setTasks(prev => [task, ...prev])
      setActiveTaskId(task.id)
      setPrompt("")
      toast({ title: "任务已提交" })
    } catch (err: any) {
      toast({ title: "提交失败", description: err.message, variant: "destructive" })
    } finally { setSubmitting(false) }
  }

  const handleCreateProject = async (name: string) => {
    try {
      const proj = await taskAPI.createProject(name)
      setProjects(prev => [...prev, proj])
      setActiveProject(proj)
      toast({ title: `项目「${name}」已创建` })
    } catch (err: any) {
      toast({ title: "创建失败", description: err.message, variant: "destructive" })
    }
  }

  return (
    <div className="flex h-full overflow-hidden bg-background">

      {/* ── Left sidebar ──────────────────────────────────────────────────── */}
      <div className="w-60 shrink-0 border-r border-border/50 flex flex-col bg-muted/[0.15]">
        {/* Top nav */}
        <div className="p-3 space-y-0.5 border-b border-border/40">
          {[
            { icon: <Plus className="h-4 w-4" />,    label: "新建任务",  action: () => setActiveTaskId(null) },
            { icon: <Search className="h-4 w-4" />,   label: "搜索",     action: () => {} },
          ].map(item => (
            <button key={item.label} onClick={item.action}
              className="flex items-center gap-2.5 w-full px-2.5 py-2 rounded-lg text-sm text-muted-foreground hover:text-foreground hover:bg-foreground/[0.05] transition-colors">
              {item.icon}{item.label}
            </button>
          ))}
        </div>

        {/* Projects */}
        <div className="flex-1 overflow-y-auto py-2">
          <div className="px-3 py-1.5 flex items-center justify-between">
            <span className="text-[11px] text-muted-foreground/50 font-medium uppercase tracking-wider">项目</span>
            <button onClick={() => setShowNewProject(true)}
              className="h-5 w-5 flex items-center justify-center rounded text-muted-foreground hover:text-foreground hover:bg-foreground/[0.06] transition-colors">
              <FolderPlus className="h-3.5 w-3.5" />
            </button>
          </div>

          {projects.map(proj => {
            const ptasks   = tasks.filter(t => t.branch === proj.name || (proj.name === "默认工作区" && !t.branch))
            const running  = ptasks.filter(t => t.status === 1).length
            const isActive = activeProject?.name === proj.name
            return (
              <div key={proj.name}>
                <button onClick={() => { setActiveProject(proj); setActiveTaskId(null) }}
                  className={cn("flex items-center gap-2 w-full px-3 py-2 text-left transition-colors",
                    isActive ? "text-foreground" : "text-muted-foreground hover:text-foreground")}>
                  <Folder className="h-4 w-4 shrink-0" />
                  <span className="text-sm font-medium truncate flex-1">{proj.name}</span>
                  {proj.is_git && <GitBranch className="h-3 w-3 text-muted-foreground/40 shrink-0" />}
                  {running > 0 && (
                    <span className="h-4 w-4 rounded-full bg-blue-500 text-white text-[9px] font-bold flex items-center justify-center shrink-0">
                      {running}
                    </span>
                  )}
                </button>

                {isActive && ptasks.slice(0, 6).map(t => {
                  const s = STATUS[t.status]
                  return (
                    <button key={t.id} onClick={() => setActiveTaskId(t.id)}
                      className={cn("flex items-center gap-2 w-full pl-9 pr-3 py-1.5 text-left transition-colors group",
                        activeTaskId === t.id ? "text-foreground bg-foreground/[0.04]" : "text-muted-foreground/70 hover:text-muted-foreground")}>
                      <span className={cn("shrink-0", s.color)}>{s.icon}</span>
                      <span className="text-xs truncate flex-1">{t.title}</span>
                      <span className="text-[10px] text-muted-foreground/40 shrink-0">{timeAgo(t.create_time)}</span>
                    </button>
                  )
                })}
              </div>
            )
          })}
        </div>

        <div className="p-3 border-t border-border/40">
          <button className="flex items-center gap-2.5 w-full px-2.5 py-2 rounded-lg text-sm text-muted-foreground hover:text-foreground hover:bg-foreground/[0.05] transition-colors">
            <Settings2 className="h-4 w-4" />设置
          </button>
        </div>
      </div>

      {/* ── Main ──────────────────────────────────────────────────────────── */}
      <div className="flex-1 min-w-0 flex flex-col overflow-hidden">
        {!activeProject ? (
          <div className="flex-1 flex flex-col items-center justify-center gap-5">
            <Folder className="h-12 w-12 text-muted-foreground/20" />
            <div className="text-center">
              <h2 className="text-lg font-semibold mb-1">选择或创建项目</h2>
              <p className="text-sm text-muted-foreground">在左侧选择已有项目，或点击 <span className="text-foreground">+</span> 新建</p>
            </div>
            <Button onClick={() => setShowNewProject(true)} className="gap-2">
              <FolderPlus className="h-4 w-4" />新建项目
            </Button>
          </div>
        ) : (
          <>
            {/* Scroll area */}
            <div className="flex-1 overflow-y-auto flex flex-col items-center justify-center px-8 py-12">
              <div className="w-full max-w-2xl">
                {/* Title */}
                <h1 className="text-2xl font-semibold text-center mb-10">
                  我们该在{" "}
                  <span className="text-foreground">{activeProject.name}</span>
                  {" "}中做什么？
                </h1>

                {/* Project info bar */}
                <div className="flex items-center gap-3 text-xs text-muted-foreground mb-6 justify-center">
                  <span className="flex items-center gap-1">
                    <FileText className="h-3.5 w-3.5" />{activeProject.files} 个文件
                  </span>
                  {activeProject.is_git && (
                    <span className="flex items-center gap-1 text-green-500">
                      <GitBranch className="h-3.5 w-3.5" />Git 仓库
                    </span>
                  )}
                  <span className="font-mono text-muted-foreground/50 truncate max-w-[240px]">{activeProject.path}</span>
                </div>

                {/* Recent tasks */}
                {projectTasks.length > 0 && (
                  <div className="space-y-1.5 mb-8">
                    {projectTasks.slice(0, 5).map(t => {
                      const s = STATUS[t.status]
                      return (
                        <button key={t.id} onClick={() => setActiveTaskId(t.id)}
                          className="flex items-center gap-3 w-full px-4 py-3 rounded-xl bg-muted/30 hover:bg-muted/50 border border-border/30 hover:border-border/60 transition-all text-left group">
                          <span className={cn("shrink-0", s.color)}>{s.icon}</span>
                          <span className="flex-1 text-sm text-foreground/80 truncate group-hover:text-foreground">{t.title}</span>
                          <span className="text-xs text-muted-foreground/40 shrink-0">{timeAgo(t.create_time)}</span>
                          <ChevronRight className="h-4 w-4 text-muted-foreground/30 group-hover:text-muted-foreground shrink-0" />
                        </button>
                      )
                    })}
                  </div>
                )}

                {/* Suggestions (empty state) */}
                {projectTasks.length === 0 && (
                  <div className="grid grid-cols-2 gap-2 mb-8">
                    {SUGGESTIONS.slice(0, 4).map((s, i) => (
                      <button key={i} onClick={() => setPrompt(s)}
                        className="text-left px-3 py-2.5 rounded-xl border border-border/40 hover:border-border/80 hover:bg-muted/30 transition-all text-sm text-muted-foreground hover:text-foreground">
                        {s}
                      </button>
                    ))}
                  </div>
                )}
              </div>
            </div>

            {/* Input bar */}
            <div className="border-t border-border/40 bg-background px-8 py-4 shrink-0">
              <div className="max-w-2xl mx-auto">
                <div className="rounded-2xl border border-border/60 bg-muted/20 focus-within:border-foreground/20 focus-within:bg-background transition-all shadow-sm">
                  <Textarea
                    value={prompt}
                    onChange={e => setPrompt(e.target.value)}
                    placeholder={`向 ${activeProject.name} 提交一个任务...`}
                    rows={2}
                    className="resize-none border-0 bg-transparent shadow-none text-sm px-4 pt-3.5 pb-2 focus-visible:ring-0"
                    onKeyDown={e => {
                      if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') {
                        e.preventDefault(); handleSubmit()
                      }
                    }}
                  />
                  <div className="flex items-center justify-between px-3 pb-3 pt-0">
                    {/* Model chips */}
                    <div className="flex items-center gap-1 flex-wrap">
                      {profiles.map(p => (
                        <button key={p.id} onClick={() => setSelectedProfileId(p.id)}
                          className={cn("flex items-center gap-1 px-2 py-1 rounded-lg text-xs transition-all",
                            selectedProfileId === p.id
                              ? "bg-foreground text-background font-medium"
                              : "text-muted-foreground hover:text-foreground hover:bg-foreground/[0.05]")}>
                          {p.chat_model_icon_url && (
                            // eslint-disable-next-line @next/next/no-img-element
                            <img src={p.chat_model_icon_url} alt="" className="h-3.5 w-3.5 rounded-sm object-contain" />
                          )}
                          {p.name}
                        </button>
                      ))}
                    </div>
                    <Button size="icon" className="h-8 w-8 rounded-xl shrink-0"
                      onClick={handleSubmit}
                      disabled={!prompt.trim() || !selectedProfileId || submitting}>
                      {submitting
                        ? <Loader2 className="h-4 w-4 animate-spin" />
                        : <ArrowUp className="h-4 w-4" />}
                    </Button>
                  </div>
                </div>
                <p className="text-center text-[11px] text-muted-foreground/40 mt-2">⌘↵ 提交</p>
              </div>
            </div>
          </>
        )}
      </div>

      {/* Task panel (slide-in from right) */}
      {activeTask && (
        <>
          <div className="fixed inset-0 z-30" onClick={() => setActiveTaskId(null)} />
          <TaskPanel
            task={activeTask}
            onClose={() => setActiveTaskId(null)}
            onRefresh={async () => {
              try {
                const updated = await taskAPI.get(activeTask.id)
                setTasks(prev => prev.map(t => t.id === activeTask.id ? updated : t))
              } catch {}
            }}
          />
        </>
      )}

      <NewProjectDialog
        open={showNewProject}
        onClose={() => setShowNewProject(false)}
        onCreate={handleCreateProject}
      />
    </div>
  )
}
